version: 0.2

phases:
  pre_build:
    commands:
      - echo "Connecting to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 084828593912.dkr.ecr.ap-southeast-1.amazonaws.com
      - export REPOSITORY_URI=084828593912.dkr.ecr.ap-southeast-1.amazonaws.com/demo
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t demo .
      - docker tag demo:latest 084828593912.dkr.ecr.ap-southeast-1.amazonaws.com/demo:latest

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker images..."
      - docker push 084828593912.dkr.ecr.ap-southeast-1.amazonaws.com/demo:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"simple-app","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
